server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false # 🟢 EKLENECEK: bu satır eksikti, hatayı bu tetikliyor
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

